# Sets the path for the sample files used to determine the SCC System ID when uploading data to the Single Calculus Chain:
scc_configurations_folder: data/Samples

# Path to the Licel lidar system extra parameters, needed for creating the NetCDF files required by Single Calculus Chain.
# You can either supply a file for every system ID, or you can supply multiple files for each system ID for different
# file format versions and/or time intervals (useful if the system configuration has changed).
# Supported file format versions are 1 for the older specification Licel raw data files, and 2 for the newer specification.
# Version 0 means that file can be used for any Licel raw data file format.
# Please check the atmospheric-lidar package documentation for more information on the required contents of these files.
licel_netcdf_parameters:
    310: conf/system/rali_netcdf_parameters 2020.py
    312: conf/system/rali_netcdf_parameters 2020.py
    375:
        - file: conf/system/ipral_netcdf_parameters_375-376-377-378_auto.py
          version: 1
        - file: conf/system/ipral_netcdf_parameters_375-376-377-378_auto_v2.py
          version: 2
    591:
        - file: conf/system/alpha_netcdf_parameters.py
          version: 1
        - file: conf/system/alpha_netcdf_parameters_v2.py
          version: 2
          until: 2022-01-01
        - file: conf/system/alpha_netcdf_parameters_v2_2022.py
          version: 2
          from: 2022-01-01
    610:
        - file: conf/system/alpha_netcdf_parameters.py
          version: 1
        - file: conf/system/alpha_netcdf_parameters_v2.py
          version: 2
          until: 2022-01-01
        - file: conf/system/alpha_netcdf_parameters_v2_2022.py
          version: 2
          from: 2022-01-01

# This parameter will be used to identify real measurements. The algorithm will look for these strings in the location field
# in the raw Licel files. In this sample, only "Buchares" and "SIRTA" measurements will be processed.
measurement_identifiers:
    - SIRTA
    - Buchares

# This parameter will be used to identify dark files. The algorithm will look for this string in the location field
# in the raw Licel files. In this sample, dark measurements will use "Dark" location:
dark_identifiers:
    - Dark
    - D

# This folder will hold the converted NetCDF files, which can be uploaded to the Single Calculus Chain:
netcdf_out_folder: data/netcdf

# The directory where to download SCC products:
scc_output_dir: scc_output

# The HTTP username and password that is needed to access the SCC site:
scc_basic_credentials: ['sccuser', 'sccpassword']

# The username and password that is needed to log in to the SCC site:
scc_website_credentials: ['username', 'password']

# SCC base URL. Normally you shouldn't need to change this:
scc_base_url: https://scc.imaa.cnr.it/

# Number of retries in case of connection issues when trying to upload measurements to the Single Calculus Chain:
scc_maximum_upload_retries: 3

# Maximum accepted time gap (in seconds) between two raw data files. Two data files with a time gap below this value will be
# considered as being part of the same measuremnt. A time gap above this value will signal a pause between two different measurements:
maximum_measurement_gap: 600

# Minimum time length (in seconds) for a measurement to be taken into account for further processing. This option is useful for
# filtering incomplete measurements when the instrument was turned off.
minimum_measurement_length: 1800

# Maximum time length (in seconds) for a measurement. Continuous measurements will be split at this length. This option is useful for
# setting the maximum length of a measurement to be uploaded to the Single Calculus Chain (usually 1 hour, or 3600 seconds).

maximum_measurement_length: 3600

# Determines how the algorithm will split the measurements when building the NetCDF files. One of the following values is accepted:
# [ -1, 0, 1, 2, 3 ]
# 
# -1 -- will split them based only on measurement length. When the maximum length is reached, the set will be split.
# 0  -- will center the measurement sets at sharp (xx:00) hours. The rule will not be enforced to the first and last measurements in a set.
#       Any remaining data will be glued at the beginning or end of the set.
# 1  -- behaves like 0 but will not glue any data before or after the aligned segments.
# 2  -- will center the measurement sets at half (xx:30) hours. The rule will not be enforced to the first and last measurements in a set.
#       Any remaining data will be glued at the beginning or end of the set.
# 3  -- behaves like 2 but will not glue any data before or after the aligned segments.
measurement_alignment_type: 0

# You can define test files lists using the test_TESTTNAME convention. Each item in the list
# corresponds to the location parameter written in the raw file header when the test is run.
# This will identify raw test files based on location information and copies them to the "tests" folder.
# Tests are considered valid and will be copied only if the entire list of
# tests is present.
test_Telecover:
    - 'Telecove'
    
test_Depolarisation:
    - '+45'
    - '-45'

# When using the --debug command line parameter, raw files will be copied to the specified folder
# in order to verify how the measurements were split before being converted to SCC NetCDF files:
measurements_debug_dir: data/measurement_debug